### ISSUE TITLE
Target tracking alarms use ProvisionedConcurrencyUtilization with wrong statistic 

### ISSUE THREAD

**Issue by fxgtt** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#13]
Hi,

I found that the created target tracking alarms use the ProvisionedConcurrencyUtilization metric with an "average" statistic. In the [Lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html) it is clearly stated, that the concurrency metrics have to be viewed with the "maximum" statistic to evaluate if one is hitting concurrency limits.

I understand that this metric is automatically created by using the predefined LambdaProvisionedConcurrencyUtilization metric provided by AWS application auto scaling.

With the statistic set to "average" it is not possible for auto scaling to work correctly resulting in under provisioning  which leads to constant cold starts of lambda functions. Observable with the provisioned concurrency spillover metric.

I cannot understand how with the "average" statistic the auto scaling ever worked and this feels really odd to me. Am I missing something?

**Comment by claydanford** [comment]
Hi @fxgtt, Thank you for the comment. This works fine using the average statistic, but would need to be tweaked to accommodate a faster scaling. For workloads with spikes, you are correct it is more difficult to scale with this metric.

Ultimately it is up to AWS to correct or change the metric as it is not controlled by the module.

Alternatively adding configuration for step scaling as an option is welcome, please feel free to open a PR.

Kindly,

CRD

**Comment by fxgtt** [comment]
@claydanford Thank you for clearing this up. I guess my invocation pattern is spiky. 

I do not know if step scaling is needed. For my use case I think it would suffice if I could simply decide which statistic I want to use with the target tracking policy.

I would propose to use the CustomizedMetricSpecification instead of the PredefinedMetricSpecification. Create a custom metric with the same values like the current configuration but making the statistic configurable defaulting to "average". This way it is backwards compatible and a rather small change.

What do you think?

**Comment by claydanford** [comment]
@fxgtt, adding CustomizedMetricSpecification as an option is welcome, but should default to the PredefinedMetricSpecification. This can be controlled by additional, optional `serverless.yml` configuration.

I'm happy to assist where I can.

If you have a contact at AWS, feel free to send them a note on why the predefined metric is incorrectly configured and what should be updated.

Kindly,

CRD

**Comment by fxgtt** [comment]
Sounds good to me.

I am already in exchange with AWS about this issue. 

One thought about still using the predefined metric: If AWS decides to change the statistic this will catch the users by surprise because the auto scaling behaviour will change drastically without them updating this plugin. Using a custom metric would safeguard against changes like that but of course also adds more responsibility.

For me it is fine either way though and I will give it a shot.

Just to be clear about how you would want the configuration to look like. I think I will be able to work backwards from that. Did you thought about something like this?

`
concurrencyAutoscaling:
    enabled: true
    maximum: 10
    minimum: 1
    usage: 0.75
    scaleInCooldown: 120
    scaleOutCooldown: 0
    metric: 
        statistic: maximum`

If metric is not set the predefined metric is used. 

Should it be possible to configure more than just the statistic?

**Comment by claydanford** [comment]
Understood about AWS changing things. I consider that something AWS has to deal with. We sit on the side of the users, unless it involves developing the plugin.

Regarding configuration, I think you're on the right path. I would change `metric` to `customMetric` and default it to a boolean with sensible defaults.  Then override values as an option, similar to the original implementation. Let me know if this point needs clarification. Feel free to MVP this with just the boolean.

I've never set up this type of custom metric on a lambda utilization before so my help in cloudwatch will be limited. Glad to assist otherwise.

Example:

```YAML
concurrencyAutoscaling:
    enabled: true
    customMetric: true

###

concurrencyAutoscaling:
    enabled: true
    customMetric: 
        statistic: maximum
        etc...
```
