### ISSUE TITLE
Scheduling provisioned concurrency

### ISSUE THREAD

**Issue by ptrhck** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#16]
Many thanks for this great plugin! As far as I can see, your plugin does not offer [scheduling provisioned concurreny](https://aws.amazon.com/de/blogs/compute/scheduling-aws-lambda-provisioned-concurrency-for-recurring-peak-usage/). Am I right? Do you have any plans on adding this optionallity?

Cheers!

**Comment by claydanford** [comment]
Hi @ptrhck, thank you for the comment.

Scheduling is not featured in this plugin but PR's are welcome for add this. Please let me know if you have any questions.

I am currently working on schema validation which is pending a PR with the `@types/serverless`.

**Comment by claydanford** [comment]
@hemanthj This can be closed due to lack of feedback.
