### ISSUE TITLE
Add doc to fields

### ISSUE THREAD

**Issue by lusatiro** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#18]
Hi, congrats on the awesome project!

I think that it could be more descriptive. I had to search on AWS docs to know what [ScaleInCooldown](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_TargetTrackingScalingPolicyConfiguration.html) means for example. I know it can be silly but makes the difference. I can open a PR to add this if you want.

**Comment by claydanford** [comment]
Hi @lusatiro 👋🏼

Thanks for the comment. Yes this would be a great addition to the docs, and a PR is welcome. My suggestion would be to link the official AWS documentation instead of recreating it. Cheers!

**Comment by lusatiro** [comment]
That's nice. Another question, `minimum` and `provisionedConcurrency` should have the same value?

**Comment by claydanford** [comment]
Good question. With autoscaling enabled, `provisionedConcurrency` acts as an initial desired count. If you set it to 5 but `minimum` to 1, it could scale down to 1.

After typing this out I suppose there is a scenario where the configured `provisionedConcurrency` is different than what is in the account. In which case it would change during a deployment. I have not experienced an issue with this but there could be issue if doing a deployment where the configured `provisionedConcurrency` is lower than what is needed, say during peak times.

**Comment by claydanford** [comment]
@hemanthj This can be closed for lack of activity.
