### ISSUE TITLE
Error deploying my lambda function with the plugin: FUNCTION_ERROR_INIT_FAILURE

### ISSUE THREAD

**Issue by tofredi** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#23]
Hi there! I'm getting the following error when I try to deploy my function with the plugin

```
Serverless Error ---------------------------------------    

An error occurred: AppProvConcLambdaAlias - Provisioned Concurrency configuration failed to be applied. Reason: FUNCTION_ERROR_INIT_FAILURE
```

Any idea on how to debug this error?

**Comment by claydanford** [comment]
Hi, @tofredi this is common when your code has an issue and lambda cannot initialize correctly. If you remove the plugin, but leave provisioned concurrency, you will see the same error.

**Comment by tofredi** [comment]
Yes, I have just fixed the error
Thanks @claydanford

**Comment by talaikis** [comment]
Removing plugin, actually, solves this problem.
