### ISSUE TITLE
Configuration schema extension does not pass strict validation mode

### ISSUE THREAD

**Issue by pgrzesik** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#28]
Hello,

along with the upcoming `v3` release of the Serverless Framework, internal schema validation has been improved and now enforces `strict` validation mode. Unfortunately, after preliminary tests, it seems like the schema extension implemented in this plugin does not adhere to strict validation rules and needs to be adjusted in order to support `v3` release of the Framework. The best way to verify that is to use the plugin along with the latest `v3` prerelease (or official release soon). 

I'm happy to answer any additional questions.

**Comment by pgrzesik** [comment]
Hello @claydanford 👋 There's no specific Framework docs, but in `v3` we upgraded `ajv` to `v8` and enforced strict schema validation with the following settings:
```
strict: true,
strictRequired: false,
```

The best information about what that means can be found here: https://ajv.js.org/strict-mode.html

Honestly, the best way to address it is to just try to run plugin with v3 Framework and see the error that will pop up - as the plugin only adds a few properties it should be quite easy to address. 

If you have any additional questions please let me know 💯

**Comment by claydanford** [comment]
@pgrzesik Thanks for the feedback. It worked as you said. I opened #29 to resolve.

**Comment by pgrzesik** [comment]
Happy to hear that @claydanford 🙌 Thanks for addressing it so quickly 🙇
