### ISSUE TITLE
Refactor resource names to match serverless standards

### ISSUE THREAD

**Issue by claydanford** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#38]
Serverless creates resources named`{FunctionPrefix}{ResourceType}`.
Examples:
- `Hello2LambdaFunction`
- `Hello2LogGroup`
- `Hello2ProvConcLambdaAlias`

This plugin creates resources named `{ServiceName}{FunctionName}{ResourceType}{Stage}{Region}`.
Examples:
- `SlstestHello2AutoScalingPolicyDevUseast1`
- `SlstestHello2AutoScalingTargetDevUseast1`

Would be good to update the plugin to match sls.

**Comment by cookieMr** [comment]
@claydanford 
i believe this should be reopened
and released in 2.0.0 (prefferebly with few other breaking changes to limit new major versions)
