### ISSUE TITLE
Update Serverless (dev) dependency to v3

### ISSUE THREAD

**Issue by cookieMr** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#45]
This plugin uses v1. Current version is v3.

This might be a contract breaking change. So i suggest to prepare it along with other changes for v2.0.0 of this plugin.

**Comment by claydanford** [comment]
Since this is just for types, dev dep, we don't need to version for v2.0.0.

**Comment by claydanford** [comment]
@nmrad-91 This can be closed due to lack of response.
