### ISSUE TITLE
Prepare a Schema Validation for the Configuration

### ISSUE THREAD

**Issue by cookieMr** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#46]
Prepare schema for Provisioned Concurrency config to leverage SLS schema validation.

- [AWS uses Draft 04](https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html#models-mappings-models)
- [Serverless can validate configuration against Schema with AVJ](https://www.serverless.com/framework/docs/configuration-validation)

This might be a contract breaking change. So i suggest to prepare it along with other changes for v2.0.0 of this plugin.

**Comment by claydanford** [comment]
This was already implemented: https://github.com/neiman-marcus/serverless-provisioned-concurrency-autoscaling/blob/master/src/plugin.ts#L40

**Comment by cookieMr** [comment]
i mean it to be a little bit more specific than just an object with unspecified fields
few more levels
