### ISSUE TITLE
Failed Alb Target Group

### ISSUE THREAD

**Issue by arleyyap** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#50]
I have been using this plugin for a short time but I have a question because I get the following error when trying to update the Alb's target group:
`ElasticLoadBalancerV2 TargetGroup did not stabilize.`

This error is only generated when the stack and the lambda function have already been created. If I create the stack from scratch it is created correctly.

I am using:
```
Framework Core: 3.20.0 (local) 3.21.0 (global)
Plugins: 6.2.2
SDK: 4.3.2
```

And just the basic configuration in the lambda:
```
provisionedConcurrency: 1
   concurrencyAutoscaling: true
```

**Comment by claydanford** [comment]
Hi @arleyyap, thanks for the comment. Not sure why this would be happening. This plugin only creates some autoscaling configuration. Any other details you can provide?

**Comment by claydanford** [comment]
@nmrad-91 This can be closed due to lack of response.
