### ISSUE TITLE
Unable to deploy autoscaling with provisioned concurrency

### ISSUE THREAD

**Issue by rajiniganth** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#52]
We have added the below configuration to the existing lambda to enable autoscaling on provisioned concurrency. We are seeing deployment error stating that function:xxxxxx-xxxx:provisioned|lambda:function:ProvisionedConcurrency|lambda already exists. Even though there is no provisioned concurrency setup on the existing lambda.

provisionedConcurrency: 1
concurrencyAutoscaling:
     enabled: true
     maximum: 1
     minimum: 10
     usage: 0.75
     scaleInCooldown: 120
     scaleOutCooldown: 0

We are using the below version of the plugins: 
"serverless": "2.72.3",
    "serverless-aws-documentation": "1.1.0",
    "serverless-iam-roles-per-function": "3.1.0",
    "serverless-plugin-lambda-insights": "^1.0.10",
    "serverless-prune-plugin": "^1.5.1",
    "serverless-plugin-conditional-functions": "^1.0.6",
    "serverless-provisioned-concurrency-autoscaling": "1.9.1"

**Comment by claydanford** [comment]
Hi @rajiniganth did this get resolved? Usually it's because there is another deployment of some sort.

**Comment by AbhinavA1990** [comment]
Hi @claydanford I checked the scalable targets in the account, they were empty using the following cli command.

aws application-autoscaling describe-scalable-targets --service-namespace lambda

Prior to the deployment none were found. Still during the deployment, I get the same error as stated above 

unction:xxxxxx-xxxx:provisioned|lambda:function:ProvisionedConcurrency|Scalable-target already exists. 

We are using  "serverless-provisioned-concurrency-autoscaling": "^1.3.2", version

**Comment by claydanford** [comment]
@AbhinavA1990 Can you try updating to the latest version? What happens if you remove the stack? Thx.

**Comment by claydanford** [comment]
@nmrad-91 This is okay to close due to lack of activity.
