### ISSUE TITLE
Unable to set dynamic provisioned concurrency using serverless.ts

### ISSUE THREAD

**Issue by trent-dailey** [neiman-marcus/serverless-provisioned-concurrency-autoscaling#53]
Instead of using serverless.yml files we use serverless.ts files since our code is written in typescript and we wanted to keep things consistent. However this has caused a problem with being able to dynamically set the number of provisioned concurrency on deployment. We need this functionality as we do not need as much, or any, provisioned concurrency in non-production but do need it for production. Below is a snippet of our index.ts file for our helloworld lambda using serverless framework.

```
import schema from "./schema";
import { handlerPath } from "@libs/handlerResolver";
import { getProvisionedConfig } from "../../../provisionedConfig";

export default {
  handler: `${handlerPath(__dirname)}/handler.main`,
  provisionedConcurrency: parseInt("${self:custom.envConfig.helloProvisionedMin}"),
  // provisionedConcurrency: getProvisionedConfig().HELLO_PROVISIONED_MIN,
  concurrencyAutoscaling: {
    // attempted loading variable directly from serverless.ts file and also setting provisionedConfig.ts file for vars but neither worked.
    enabled: !!"${self:custom.envConfig.helloProvisionedAutoScaling}",
    // enabled: getProvisionedConfig().HELLO_PROVISIONED_AUTO_SCALING,
    alias: "provisioned",
    maximum: 100,
    minimum: parseInt("${self:custom.envConfig.helloProvisionedMin}"),
    // minimum: getProvisionedConfig().HELLO_PROVISIONED_MIN,
    usage: 0.75,
    scaleInCooldown: 0,
    scaleOutCooldown: 0,
    customMetric: {
      statistic: "minimum",
    },
    scheduledActions: [
      {
        name: "DailyAutoScaleOut",
        timezone: "America/New_York",
        schedule: "cron(0 9 * * ? *)",
        action: {
          maximum: 100,
          minimum: parseInt("${self:custom.envConfig.helloProvisionedMin}"),
          // minimum: getProvisionedConfig().HELLO_PROVISIONED_MIN,
        },
      },
      {
        name: "DailyAutoScaleIn",
        timezone: "America/New_York",
        schedule: "cron(00 01 * * ? *)",
        action: {
          maximum: 10,
          minimum: 1,
        },
      },
    ],
  },
  events: [
    {
      http: {
        method: "post",
        path: "hello",
        request: {
          schemas: {
            "application/json": schema,
          },
        },
      },
    },
  ],
};
```

We end up seeing this message in the serverless deploy output "Skipping Provisioned Concurrency Auto Scaling: Concurrency configuration is missing!" and the cloudformation template does not have any references to autoscaling. It appears no dynamic values will work but hardcoded values do, however that does not meet our use case.

I also attempted to set this directly in the serverless.ts file but have not been able to get that working either. Being able to dynamically set provisioned concurrency autoscaling based on the environment being deployed to should be possible. How would we be able to accomplish this?

**Comment by claydanford** [comment]
Hi @trent-dailey I am unable to recreate the issue you are experiencing. Is this still a problem? Here is the config I used to test.

```shell
➜  sls-dynamic sls -v
Running "serverless" from node_modules
Framework Core: 3.25.1 (local) 3.25.1 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

```typescript
import schema from './schema';
import { handlerPath } from '@libs/handler-resolver';

export const getProvisionedConfig = () => ({ MIN: 2, ENABLED: true });

export default {
  handler: `${handlerPath(__dirname)}/handler.main`,
  provisionedConcurrency: getProvisionedConfig().MIN,
  concurrencyAutoscaling: {
    enabled: getProvisionedConfig().ENABLED,
    minimum: getProvisionedConfig().MIN,
  },
  events: [
    {
      http: {
        method: 'post',
        path: 'hello',
        request: {
          schemas: {
            'application/json': schema,
          },
        },
      },
    },
  ],
};
```

Output:
```shell
➜  sls-dynamic sls package
Running "serverless" from node_modules

Packaging sls-dynamic for stage dev (us-east-1)
Configuring Provisioned Concurrency Auto Scaling...
 - Building Configuration for resource "lambda/hello"
Added Provisioned Concurrency Auto Scaling to CloudFormation!

✔ Service packaged (0s)
```

**Comment by trent-dailey** [comment]
Thanks @claydanford. Was able to get around the issue by using the below syntax.

`provisionedConcurrency: "${self:custom.envConfig.helloProvisionedMin}" as unknown as number,
  concurrencyAutoscaling: {
    enabled: "${self:custom.envConfig.helloProvisionedAutoScaling}",
    minimum: "${self:custom.envConfig.helloProvisionedMin}"  as unknown as number,
  },`

This is what I had to do to get around the typechecking issues. I will close out this since this has been resolved.

**Comment by claydanford** [comment]
@trent-dailey Thanks for the feedback. It looks like an issue with sls considering it is required by the built in `provisionedConcurrency` parameter also, which isn't part of the plugin.
